CREATE DATABASE sistema_alunos;
USE sistema_alunos;

CREATE TABLE alunos ( 
id INT AUTO_INCREMENT PRIMARY KEY, 
nome VARCHAR(100) NOT NULL, 
email VARCHAR(100) NOT NULL);

SELECT * FROM alunos;
DESCRIBE alunos;